Update staging-build.yml

diff --git a/.github/workflows/staging-build.yml b/.github/workflows/staging-build.yml
--- a/.github/workflows/staging-build.yml
+++ b/.github/workflows/staging-build.yml
@@ -54,11 +54,16 @@ jobs:
         run: |
           prisma=$(convox run api -a test-prisma --release ${{ steps.get_releases_id.outputs.releases_id }} npx prisma migrate deploy | sed "2 d")
           echo $prisma
-          errors=$(echo $prisma | grep Error)
-          faileds=$(echo $prisma | grep failed)
-          if [ -n "$faileds" ]
+          buildError=$(echo $prisma | grep Error)
+          buildFailed=$(echo $prisma | grep failed)
+          if [ -n "$buildFailed" ]
           then
-            echo "Convox build failed"
+            echo "Convox build failed ${{faileds}}"
+            exit 1
+          fi
+          if [ -n "$buildError" ]
+          then
+            echo "Convox build Error ${{buildError}}"
             exit 1
           fi
       
